// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceCompany.DbStuff.Postgres;

#nullable disable

namespace ServiceCompany.Migrations.ServiceCompanyPostgresDb
{
    [DbContext(typeof(ServiceCompanyPostgresDbContext))]
    [Migration("20240515184706_AddTesT11")]
    partial class AddTesT11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlertUser", b =>
                {
                    b.Property<int>("NotifiedUsersId")
                        .HasColumnType("integer");

                    b.Property<int>("SeenAlertsId")
                        .HasColumnType("integer");

                    b.HasKey("NotifiedUsersId", "SeenAlertsId");

                    b.HasIndex("SeenAlertsId");

                    b.ToTable("AlertUser");
                });

            modelBuilder.Entity("CategoryEntityParameterEntity", b =>
                {
                    b.Property<int>("CategoryParametersId")
                        .HasColumnType("integer");

                    b.Property<int>("ParameterCategoriesId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryParametersId", "ParameterCategoriesId");

                    b.HasIndex("ParameterCategoriesId");

                    b.ToTable("CategoryEntityParameterEntity");
                });

            modelBuilder.Entity("ElementEntityMaterialEntity", b =>
                {
                    b.Property<int>("ElementsId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialsId")
                        .HasColumnType("integer");

                    b.HasKey("ElementsId", "MaterialsId");

                    b.HasIndex("MaterialsId");

                    b.ToTable("ElementEntityMaterialEntity");
                });

            modelBuilder.Entity("ElementEntityParameterEntity", b =>
                {
                    b.Property<int>("ElementsId")
                        .HasColumnType("integer");

                    b.Property<int>("ParametersId")
                        .HasColumnType("integer");

                    b.HasKey("ElementsId", "ParametersId");

                    b.HasIndex("ParametersId");

                    b.ToTable("ElementEntityParameterEntity");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.BasePointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BasePoints");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.DesignOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DesignOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DesignOptions");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ElementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Angle")
                        .HasColumnType("double precision");

                    b.Property<string>("BaseLevel")
                        .HasColumnType("text");

                    b.Property<string>("Building")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassifierPosition")
                        .HasColumnType("text");

                    b.Property<string>("ConstructionMaterial")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DesignOption")
                        .HasColumnType("text");

                    b.Property<string>("DesignOptionId")
                        .HasColumnType("text");

                    b.Property<double?>("Diameter")
                        .HasColumnType("double precision");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ElementId")
                        .HasColumnType("integer");

                    b.Property<string>("ElementType")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<string>("Floor")
                        .HasColumnType("text");

                    b.Property<int?>("GridEntityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("IdInCatalog")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacture")
                        .HasColumnType("text");

                    b.Property<string>("Mark")
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameInCatalog")
                        .HasColumnType("text");

                    b.Property<bool?>("OnNavisworksView")
                        .HasColumnType("boolean");

                    b.Property<double?>("Perimeter")
                        .HasColumnType("double precision");

                    b.Property<string>("PhaseCreated")
                        .HasColumnType("text");

                    b.Property<string>("PhaseDemolished")
                        .HasColumnType("text");

                    b.Property<double?>("Radius")
                        .HasColumnType("double precision");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("SetPosition")
                        .HasColumnType("text");

                    b.Property<string>("SettingLevel")
                        .HasColumnType("text");

                    b.Property<double?>("Square")
                        .HasColumnType("double precision");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.Property<string>("WBSPosition")
                        .HasColumnType("text");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision");

                    b.Property<string>("WorkSet")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("GridEntityId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TypeId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ElementTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ElementId")
                        .HasColumnType("integer");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParameterEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ParameterEntityId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.GridEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("GridId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("LocationX")
                        .HasColumnType("double precision");

                    b.Property<double>("LocationY")
                        .HasColumnType("double precision");

                    b.Property<double>("LocationZ")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ElementTypeId");

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.LevelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("Elevation")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ElementTypeId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<double>("Elevation")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeatherStation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.MaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Square")
                        .HasColumnType("double precision");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ParameterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GIUD")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParameterCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("integer");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.RevitCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RevitCategoryEntities");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.UserWorkSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkSetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("WorkSets");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ViewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnSheet")
                        .HasColumnType("boolean");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewId")
                        .HasColumnType("integer");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DocumentId");

                    b.ToTable("Views");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.Warning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.WarningElementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ElementId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WarningId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WarningId");

                    b.ToTable("WarningElements");
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ThumbsDown")
                        .HasColumnType("integer");

                    b.Property<int?>("ThumbsUp")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea");

                    b.Property<int?>("BankAccount")
                        .HasColumnType("integer");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<double>("FinBalance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.MemberRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MemberRoles");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MemberRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferLocalLang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MemberRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ExecutorId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("StatusId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.UserTaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskStatuses");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Postgres.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NNam")
                        .HasColumnType("text");

                    b.Property<List<int>>("NamIds")
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("ServiceCompanyChatService.DbStuff.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("CommentMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("AlertUser", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.User", null)
                        .WithMany()
                        .HasForeignKey("NotifiedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCompany.DbStuff.Models.Alert", null)
                        .WithMany()
                        .HasForeignKey("SeenAlertsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryEntityParameterEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ParameterEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("ParameterCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElementEntityMaterialEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ElementEntity", null)
                        .WithMany()
                        .HasForeignKey("ElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.MaterialEntity", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElementEntityParameterEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ElementEntity", null)
                        .WithMany()
                        .HasForeignKey("ElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ParameterEntity", null)
                        .WithMany()
                        .HasForeignKey("ParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Categories")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.DesignOptionEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("DesignOptions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ElementEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", "Category")
                        .WithMany("Elements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Elements")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.GridEntity", null)
                        .WithMany("Elements")
                        .HasForeignKey("GridEntityId");

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.LevelEntity", "Level")
                        .WithMany("Elements")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ElementTypeEntity", "Type")
                        .WithMany("Elements")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Document");

                    b.Navigation("Level");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ElementTypeEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", "Category")
                        .WithMany("ElementTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("ElementTypes")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ParameterEntity", null)
                        .WithMany("Types")
                        .HasForeignKey("ParameterEntityId");

                    b.Navigation("Category");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.GridEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Grids")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ElementTypeEntity", "ElementType")
                        .WithMany("Grids")
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Document");

                    b.Navigation("ElementType");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.LevelEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Levels")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.ElementTypeEntity", "ElementType")
                        .WithMany("Levels")
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Document");

                    b.Navigation("ElementType");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.LocationEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Locations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.MaterialEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Materials")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ParameterEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Parameters")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.UserWorkSet", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("WorkSets")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ViewEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Views")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.Warning", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", "Document")
                        .WithMany("Warnings")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.WarningElementEntity", b =>
                {
                    b.HasOne("ManagementCompany.DbStuff.ExternalEntities.Warning", "Warning")
                        .WithMany("FailureElements")
                        .HasForeignKey("WarningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warning");
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCompany.DbStuff.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Alert", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.User", "Author")
                        .WithMany("CreatedAlerts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Article", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.User", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Company", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.User", "Author")
                        .WithMany("CreatedCompanies")
                        .HasForeignKey("AuthorId");

                    b.HasOne("ServiceCompany.DbStuff.Models.CompanyProfile", "Profile")
                        .WithOne("Company")
                        .HasForeignKey("ServiceCompany.DbStuff.Models.Company", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("CompanyId");

                    b.Navigation("Author");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Project", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.User", "Author")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServiceCompany.DbStuff.Models.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.User", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.Article", null)
                        .WithMany("Watchers")
                        .HasForeignKey("ArticleId");

                    b.HasOne("ServiceCompany.DbStuff.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("ServiceCompany.DbStuff.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServiceCompany.DbStuff.Models.UserProfile", "Profile")
                        .WithOne("User")
                        .HasForeignKey("ServiceCompany.DbStuff.Models.User", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("UserId");

                    b.HasOne("ServiceCompany.DbStuff.Models.MemberRole", "MemberRole")
                        .WithMany("Users")
                        .HasForeignKey("MemberRoleId");

                    b.Navigation("Author");

                    b.Navigation("Company");

                    b.Navigation("MemberRole");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.UserTask", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.User", "Author")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServiceCompany.DbStuff.Models.User", "Executor")
                        .WithMany("ExecutedTasks")
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServiceCompany.DbStuff.Models.UserTaskStatus", "Status")
                        .WithMany("UserTasks")
                        .HasForeignKey("StatusId");

                    b.Navigation("Author");

                    b.Navigation("Executor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ServiceCompanyChatService.DbStuff.Models.Comment", b =>
                {
                    b.HasOne("ServiceCompany.DbStuff.Models.Article", null)
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.CategoryEntity", b =>
                {
                    b.Navigation("ElementTypes");

                    b.Navigation("Elements");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.DocumentEntity", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("DesignOptions");

                    b.Navigation("ElementTypes");

                    b.Navigation("Elements");

                    b.Navigation("Grids");

                    b.Navigation("Levels");

                    b.Navigation("Locations");

                    b.Navigation("Materials");

                    b.Navigation("Parameters");

                    b.Navigation("Views");

                    b.Navigation("Warnings");

                    b.Navigation("WorkSets");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ElementTypeEntity", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Grids");

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.GridEntity", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.LevelEntity", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.ParameterEntity", b =>
                {
                    b.Navigation("Types");
                });

            modelBuilder.Entity("ManagementCompany.DbStuff.ExternalEntities.Warning", b =>
                {
                    b.Navigation("FailureElements");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Watchers");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Company", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.CompanyProfile", b =>
                {
                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.MemberRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.Project", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("CreatedAlerts");

                    b.Navigation("CreatedCompanies");

                    b.Navigation("CreatedProjects");

                    b.Navigation("CreatedTasks");

                    b.Navigation("ExecutedTasks");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.UserProfile", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceCompany.DbStuff.Models.UserTaskStatus", b =>
                {
                    b.Navigation("UserTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
